const msgs = {
    success: {
        SUCCESS: 'Success',
        USER_REGISTERED: 'User successfully registered',
        USER_LOGGEDIN: 'User successfully logged in',
        LOGOUT: 'Logout successfull',
        CHARACTER_CREATED: 'Character successfully created',
        CHARACTER_EDITED: 'Character successfully edited',
        CHARACTER_DELETED: 'Character successfully deleted',
        SPACESHIP_CREATED: 'Spaceship successfully created',
        SPACESHIP_EDITED: 'Spaceship successfully edited',
        SPACESHIP_DELETED: 'Spaceship successfully deleted',
        WEAPON_CREATED: 'Weapon successfully created',
        WEAPON_EDITED: 'Weapon successfully edited',
        WEAPON_DELETED: 'Weapon successfully deleted',
        PLANET_CREATED: 'Planet successfully created',
        PLANET_EDITED: 'Planet successfully edited',
        PLANET_DELETED: 'Planet successfully deleted',
        MOVIE_CREATED: 'Movie successfully created',
        MOVIE_EDITED: 'Movie successfully edited',
        MOVIE_DELETED: 'Movie successfully deleted',
        STORY_CREATED: 'Story successfully created',
        STORY_EDITED: 'Story successfully edited',
        STORY_DELETED: 'Story successfully deleted'
    },
    errors: {
        ERROR_PROCESSING_REQUEST: 'Error occured processing your request',
        LOG_IN_AND_TRY_AGAIN: 'Log In and try again.',
        SOMETHING_WENT_WRONG: 'Something went wrong',
        REGISTER_FAILED: 'Failed to register user',
        USER_DOES_NOT_EXIST: 'User does not exist',
        INVALID_PASS: 'Invalid password',
        LOGIN_FAILED: 'Failed to log in user',
        CHARACTER_DOES_NOT_EXIST: 'Character does not exist, anymore',
        UNABLE_TO_CREATE_CHARACTER: 'Unable to create character',
        FAILED_TO_EDIT_CHARACTER: 'Failed to edit character',
        FAILED_TO_DELETE_CHARACTER: 'Failed to delete character',
        SPACESHIP_DOES_NOT_EXIST: 'Spaceship does not exist, anymore',
        UNABLE_TO_CREATE_SPACESHIP: 'Unable to create spaceship',
        FAILED_TO_EDIT_SPACESHIP: 'Failed to edit spaceship',
        FAILED_TO_DELETE_SPACESHIP: 'Failed to delete spaceship',
        WEAPON_DOES_NOT_EXIST: 'Weapon does not exist, anymore',
        UNABLE_TO_CREATE_WEAPON: 'Weapon to create spaceship',
        FAILED_TO_EDIT_WEAPON: 'Failed to edit weapon',
        FAILED_TO_DELETE_WEAPON: 'Failed to delete weapon',
        PLANET_DOES_NOT_EXIST: 'Planet does not exist, anymore',
        UNABLE_TO_CREATE_PLANET: 'Unable to create planet',
        FAILED_TO_EDIT_PLANET: 'Failed to edit planet',
        FAILED_TO_DELETE_PLANET: 'Failed to delete planet',
        MOVIE_DOES_NOT_EXIST: 'Movie does not exist, anymore',
        UNABLE_TO_CREATE_MOVIE: 'Unable to create movie',
        FAILED_TO_EDIT_MOVIE: 'Failed to edit movie',
        FAILED_TO_DELETE_MOVIE: 'Failed to delete movie',
        STORY_DOES_NOT_EXIST: 'Story does not exist, anymore',
        UNABLE_TO_CREATE_STORY: 'Unable to create story',
        FAILED_TO_EDIT_STORY: 'Failed to edit story',
        FAILED_TO_DELETE_STORY: 'Failed to delete story'
    },
    serverErrors: {
        BAD_REQUEST: 'Invalid request'
    }
};

module.exports = msgs;
